### PR TITLE
add templating to rancher-compose

### PR DESCRIPTION
**Pull request by sonchang**
@ibuildthecloud can you review?  thanks!

### CODE REVIEW

**Comment by ibuildthecloud** [comment]
Do you want to rebase this on master or should I do that.  We need to find an approach that allows us to keep all of the templating logic in rancher and not in libcompose

**Comment by flaccid** [comment]
+1
Usage documentation too please :)

**Comment by sonchang** [comment]
Sorry.  Just saw your comment now.  I've rebased.  I can take a look to see how to separate out the templating stuff from libcompose.  It was just easier to put it in there since it handled the 'extends' part of reading in compose files.  But I also wanted to do the substitutions earlier in the processing of the file before it becomes ServiceConfigs.  Maybe we can introduce a hook somewhere? @ibuildthecloud

**Comment by deniseschannon** [comment]
@flaccid Once this makes it to latest, we will definitely be documenting how to use it.

**Comment by ibuildthecloud** [comment]
FYI, we won't be merging this, but will keep this PR open until we resolve https://github.com/docker/libcompose/issues/40 and merge that feature instead into `rancher-compose`

**Comment by ibuildthecloud** [comment]
Closing in favor of the solution from libcompose https://github.com/docker/libcompose/pull/47

**Pull request closed without merging**
