### PR TITLE
Provides Alternative to Amazon S3 (w/ minio lib)

### PR DESCRIPTION
**Pull request by justsml**
First I tried using the current AWS S3 SDK to connect to my minio server (using an example from Minio's docs site)
image

However I kept seeing it try connect to amazonaws.com. I'm sure I missed something. 
If anyone knows any gotchas here, please let me know.

After avoiding it, I went ahead and tried the Minio GO SDK (...looked similar enough to AWS' GO API). 
It seems to compile at the moment, tho it just won't give any console output/errors.

I was hoping a more experienced Go master could take a look.

Regarding Ticket: https://github.com/rancher/rancher/issues/2229#issuecomment-259874326

More useful reading
https://docs.minio.io/docs/how-to-run-minio-in-docker
Minio [SDK](https://docs.minio.io/docs/golang-client-api-reference), 
[Server](https://docs.minio.io/docs/minio-quickstart-guide), 
[Client](https://docs.minio.io/docs/minio-client-complete-guide).

> NB: This is my first OSS contribution for Go!
I know I probably haven't done anything the "Go way." 
Again, feedback is welcome!

### CODE REVIEW

**Comment by joshwget** [comment]
The build feature and Rancher Compose CLI in general are in the process of being deprecated. As a result, we're planning to shift towards just fixing bugs and not adding any new features.

If this PR was pretty well tested and known to be backwards compatible then I think we'd be open to merging it. It looks like it completely replaces the S3 library though, and that could cause some issues that require testing and then further development.

**Comment by justsml** [comment]
Thx @joshwget 

On the Compose CLI - is there a roadmap or blog post I can read up?

Is the `rancher-compose.yml` format still viable? 😰 

Most of my systems run w/o, however they are only cluster aware with that metadata...

**Comment by joshwget** [comment]
@justsml The file formats will remain the same. It's only the `rancher-compose` binary that will be deprecated. Instead of running `rancher-compose up` you'd just run `rancher up` from the CLI.

**Comment by justsml** [comment]
Thanks for the update @joshwget

**Pull request closed without merging**
